spring.application.name=javaspg

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=${USER_DB_ORACLE:RM565824}
spring.datasource.password=${PASSWORD_DB_ORACLE:120306}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect