spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://sqlserver-vetpet-rm565824.database.windows.net:1433;database=bd_vetpet;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fiapadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vet-pet-2026}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

#spring.security.user.name=${APP_ADMIN_USER}
#spring.security.user.password=${APP_ADMIN_PASSWORD}

spring.security.user.name=admin
spring.security.user.password=admin123